services:
  postgres-warehouse:
    image: postgres:16
    container_name: postgres-warehouse
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin@123
    ports:
      - "5432:5432"
    volumes:
      - warehouse_pgdata:/var/lib/postgresql/data

  postgres-transfer:
    image: postgres:16
    container_name: postgres-transfer
    environment:
      POSTGRES_DB: transfer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin@123
    ports:
      - "5433:5432"
    volumes:
      - transfer_pgdata:/var/lib/postgresql/data

volumes:
  warehouse_pgdata:
  transfer_pgdata:
