spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.routes[0].id=warehouse-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://warehouse-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/warehouses/**

#spring.cloud.gateway.routes[1].id=inventory-service
#spring.cloud.gateway.server.webflux.routes[1].uri=lb://warehouse-service
#spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/inventory/**

spring.cloud.gateway.server.webflux.routes[1].id=transfer-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://transfer-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/transfers/**
