server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=budget-service
spring.cloud.gateway.routes[0].uri=lb://budget-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/budgets/**

spring.cloud.gateway.routes[1].id=approval-service
spring.cloud.gateway.routes[1].uri=lb://approval-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/approvals/**

spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://budget-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**

logging.level.org.springframework.cloud.gateway=INFO